[core]
app_name = "Python Template"
environment = "Development"

[logging]
min_log_level = "INFO"
log_file_path = "restaurant_notifier_bot.log"

[restaurant]
slug = "vitrinasda"
message = "专 专专住 |  驻转 注砖 -Wolt!  https://wolt.com/he/isr/tel-aviv/restaurant/vitrina"

[telegram]
bot_token = "8102647956:AAEUBGIxdM7xwmR6t1qhti7EWo8LX8VT7U8"
chat_id = "1482185333"
