[core]
app_name = "Python Template"
environment = "Development"

[logging]
min_log_level = "INFO"
log_file_path = "restaurant_notifier_bot.log"

[restaurant]
name = "专 专专住"
url = "https://wolt.com/he/isr/tel-aviv/restaurant/vitrina"
message = "专 专专住 |  驻转 注砖 -Wolt!  https://wolt.com/he/isr/tel-aviv/restaurant/vitrina"

[telegram]
bot_token = "8329003916:AAGa3q-rKHPtEG9phILmbD_j_svGGuYROCI"
chat_id = "1482185333"
