[core]
app_name = "Python Template"
environment = "Development"

[logging]
min_log_level = "INFO"
log_file_path = "restaurant_notifier_bot.log"

[restaurant]
slug = "vitrina"
message = "专 专专住 |  驻转 注砖 -Wolt!  https://wolt.com/he/isr/tel-aviv/restaurant/vitrina"
